# Generated by Django 5.0.6 on 2024-08-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
