# Generated by Django 5.0.6 on 2024-08-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20240810_0936"),
    ]

    operations = []
